name: Build uCsim
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
        ./configure
        make
        cd picsimlab
        make